# Python 中的例外處理

_Python 語言提供了 `例外處理機制`，使設計人員用以處理可能出現的運行錯誤，透過這個機制可以編寫出更為健壯 `robust`且安全的程式碼。_



<br>

## 主要組件

1. try：嘗試執行 `可能產生錯誤` 的程式碼。
2. except：當 `例外` 或 `特定例外` 發生時執行的程式碼區塊。
3. finally： `無論是否發生錯誤` 都會執行的區塊。
4. else：當 `沒有例外` 發生時執行的區塊。
5. raise： `手動` 引發例外。

<br>

## 使用情境

1. 基本使用：僅使用 `try` + `except`。
2. 多種例外可能：一個 `try` 中有多個 except 來處理不同的例外。
3. 確定結束：使用 `finally` 確保某些程式碼最後會被執行。
4. 手動觸發：使用 `raise` 手動引發例外。
5. 完整流程：組合 `try`、`except`、`else` 和 `finally` 一起使用。

<br>

## 實作範例

<br>


1. 基本使用：`try + except`。

    _將可能產生錯誤的程式碼放在 `try` 區塊中，並使用 `except` 捕捉特定的錯誤或異常。_

    ```python
    try:
        result = 1 / 0
    except ZeroDivisionError:
        print("除數不能為 0!")
    ```
    _OUTPUT_
    ```bash
    除數不能為 0!
    ```

    _上面是直接輸出定義好的字串，若要輸出內建的異常物件訊息_

    ```python
    try:
        result = 1 / 0
    except ZeroDivisionError as e:
        print(e)
    ```
    ```bash
    division by zero
    ```

<br>

2. 多種例外：有多個 `except`。

    _可針對各種不同的錯誤可能使用不同的 `except` 區塊捕捉並進行處理。_

    ```python
    try:
        # 任意程式碼
        pass
    except TypeError:
        print("資料型態錯誤")
    except ValueError:
        print("值不合法")
    except:
        print("其他錯誤")
    ```

<br>

3. 確定結束：`try + except + finally`。

    _使用 `finally` 來確保這個區塊內的程式碼在例外處理結束前 `一定會被執行`。_

    ```python
    try:
        # some code
        pass
    except:
        # handle error
        pass
    finally:
        print("這裡的程式碼總是會被執行。")
    ```

<br>

4. 手動觸發：`raise`。

    _當需要手動引發某個特定的錯誤或異常時，可以使用 `raise`。_

    ```python
    try:
        raise ValueError("發生錯誤了!")
    except ValueError as e:
        print(f"捕捉到錯誤：{e}")
    ```

    _輸出結果_
    ```bash
    捕捉到錯誤：發生錯誤了!
    ```

<br>

5. 完整流程：`try + except + else + finally`。

    _當 `try` 區塊中的程式碼成功執行，且 `沒有任何異常` 時，`else` 區塊的程式碼會被執行。_

    ```python
    try:
        # some code
    except:
        # handle error
    else:
        # code to run if no error occurred
    finally:
        # cleanup code to run in all cases
    ```

<br>

---

_END_